name: Startup

on:
  push:
    paths-ignore:
    - '**/*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - 26.1
          - 26.2
          - 26.3
          - snapshot
    env:
      EMACS_LINT_IGNORE: ${{ matrix.lint_ignore }}
    steps:
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}

    - uses: actions/checkout@v1
    - name: Run tests
      run: 'lsb_release -a && ./test-startup.sh'

